---
grails:
    profile: web
    codegen:
        defaultPackage: blog2
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    hibernate:
        cache:
            queries: false
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ""
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mysql://127.0.0.1:3306/blogpian-grails-dev
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/blogpian-grails-test
    production:
        dataSource:
           dbCreate: "update"
           driverClassName: "org.postgresql.Driver"
           dialect: org.hibernate.dialect.PostgreSQLDialect

           uri: new URI(System.env.DATABASE_URL?:"postgres://test:test@localhost/test")

           url: "jdbc:postgresql://" + uri.host + ":" + uri.port + uri.path
           username: uri.userInfo.split(":")[0]
           password: uri.userInfo.split(":")[1]
           